language: node_js
node_js:
  - 14
  - 12
  - 10

addons:
  mariadb: '10.0'

branches:
  except:
    - /^feature\/[-\w]+$/

env:
  global:
    - CC_TEST_REPORTER_ID=c1c885065adfd5bb4901e0bb11111b73d3b71833597bc1759741e02f89b1be7b

jobs:
  include:
    - name: "ESLint"
      before_script: skip
      script: npm run lint
      after_script: skip

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  email:
    on_success: never
    on_failure: always
